plugins {
    id 'java'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

dependencies {
    implementation project(':lib')
}

jar {
    dependsOn configurations.runtimeClasspath
    manifest {
        attributes 'Main-Class': 'com.example.WebService'
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}
