/// Output module for UniversalBuild format
///
/// This module defines the data structures for the UniversalBuild format,
/// which is a declarative container build specification generated by the LLM.
pub mod schema;
pub mod dockerfile;

pub use schema::UniversalBuild;
pub use dockerfile::DockerfileGenerator;
