// Auto-generated BuildKit protobuf definitions
// Generated by build.rs from BuildKit proto files

// Include generated proto modules
pub mod moby {
    pub mod buildkit {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/moby.buildkit.v1.rs"));

            pub mod types {
                include!(concat!(env!("OUT_DIR"), "/moby.buildkit.v1.types.rs"));
            }

            pub mod sourcepolicy {
                include!(concat!(
                    env!("OUT_DIR"),
                    "/moby.buildkit.v1.sourcepolicy.rs"
                ));
            }
        }
    }

    pub mod filesync {
        pub mod v1 {
            include!(concat!(env!("OUT_DIR"), "/moby.filesync.v1.rs"));
        }
    }
}

pub mod fsutil {
    pub mod types {
        include!(concat!(env!("OUT_DIR"), "/fsutil.types.rs"));
    }
}

pub mod pb {
    include!(concat!(env!("OUT_DIR"), "/pb.rs"));
}

pub mod google {
    pub mod rpc {
        include!(concat!(env!("OUT_DIR"), "/google.rpc.rs"));
    }
}

// Re-export commonly used types and clients
pub use fsutil::types::{packet::PacketType, Packet, Stat};
pub use moby::buildkit::v1::control_client::ControlClient;
pub use moby::buildkit::v1::BytesMessage;
pub use moby::filesync::v1::auth_server::{Auth as AuthServer, AuthServer as AuthServerBuilder};
pub use moby::filesync::v1::file_send_server::{
    FileSend as FileSendServer, FileSendServer as FileSendServerBuilder,
};
pub use moby::filesync::v1::file_sync_client::FileSyncClient;
pub use moby::filesync::v1::file_sync_server::{
    FileSync as FileSyncServer, FileSyncServer as FileSyncServerBuilder,
};
